PROGRAMS = {
	% ...
};


close all; clear all; clc;
addpath('./Functions');
addpath('./Functions/Interpolation');
addpath('./Functions/Alignment');


SIGNAL_PARAMETERS = struct( ...
	'main_pulse_width', 1000, ...
	'add_side_pulse', true, ...
	'size_pulse_shift_interval', [0.25, 0.75], ...
    'IsTime_drift',true, ...
    'time_drift', 0.00001, ...
    'd',5, ...                                          % Axis time error pourcentage (%)
    'NbInterference',20, ...
    'error_width_interval', [50, 500], ...
    'oscillations_ratio_amplitude_interval', [0.01, 0.4], ...
    'oscillations_ratio_width_interval', [0.25, 1], ...
    'oscillations_freq_ratio',20, ...
    'cos_ratio_amplitude_interval', [0.25, 0.75], ...
    'cos_ratio_width_interval', [0.25, 1.5], ...
    'IsNoise',true, ...
    'noise_sigma',0.01 ...
);

main

return
for exp_n = 1:6
	% parameters
	
	for k = 1:100
		main
		
		% save results
	end
end



